#H2
spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:./src/main/resources/data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#FreeSQL

freeSQL.datasource.url=jdbc:mysql://sql5.freesqldatabase.com:3306/sql5774957?useSSL=false&serverTimezone=UTC
freeSQL.datasource.username=sql5774957
freeSQL.datasource.password=uxrJD9rVPL
freeSQL.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
freeSQL.spring.jpa.hibernate.use-new-id-generator-mappings=false
freeSQL.spring.jpa.hibernate.id.new_generator_mappings=false
spring.jpa.properties.hibernate.id.optimizer.pooled=false

freeSQL.spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


#Desactivar en prod?
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.h2.console.enabled=true

spring.jpa.properties.hibernate.show_sql=false