#H2
spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:./src/main/resources/data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#AWS

aws.datasource.url=jdbc:mysql://nutriapp-db.czsmqkkskzl3.us-east-2.rds.amazonaws.com:3306/nutriapp?useSSL=false&serverTimezone=UTC
aws.datasource.username=admin
aws.datasource.password=nutrifelicidad
aws.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
aws.spring.jpa.hibernate.use-new-id-generator-mappings=false
aws.spring.jpa.hibernate.id.new_generator_mappings=false
spring.jpa.properties.hibernate.id.optimizer.pooled=false

aws.spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


#Desactivar en prod?
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.h2.console.enabled=true

spring.jpa.properties.hibernate.show_sql=false